### ISSUE TITLE
Provide data necessary for results replication

### ISSUE THREAD

**Issue by csmutz** [uvasrg/EvadeML#1]
Could you provide the data used in your study to support replication and validation?

Specifically, providing a list of hashes for the seed malicious PDFs and the benign PDFs should allow your evaluation to be replicated with higher accuracy.

**Comment by mzweilin** [comment]
Thanks csmutz for reminding this. We should have provided the samples in the initial repo.
Checkout here: https://github.com/uvasrg/EvadeML/tree/master/samples
