### ISSUE TITLE
problem in cleverhans_models

### ISSUE THREAD

**Issue by hanwei0912** [uvasrg/EvadeML#4]
Hi,
I have an issue in clverhans_models. I install cleverhans but I find there is no conv_2d in cleverhans.utils. 
Do you have some special reference?

Thank you in advance.

**Comment by oisudfoishjf** [comment]
Hi,
I have meet the same issue. Have you solved this problem? 
Thank you.

**Comment by hanwei0912** [comment]
Hi, 
Sorry, I failed to solve it in the end.

All my best.

**Comment by mzweilin** [comment]
Hi guys, I think you were talking about the issue in another repo? https://github.com/mzweilin/EvadeML-Zoo
