### ISSUE TITLE
Errors in selection of PDFs as external genome

### ISSUE THREAD

**Issue by susobhang70** [uvasrg/EvadeML#5]
Hi! I'm trying to replicate the results from your EvadeML [GP attacks paper on PDFs](https://evademl.org/docs/evademl.pdf). I ran into a couple of issues running the code. I trained the two PDF classifier models, and when trying to run Step 2 (with Step 1 detection server running) - `./utils/generate_ext_genome.py [classifier_name] [benign_sample_folder] [file_number]` for the two classifiers, I get two different errors:

1. PDFRate
`$ ./utils/generate_ext_genome.py pdfrate ~/research/datasets/benign 1`
`Traceback (most recent call last):`
 `File "./utils/generate_ext_genome.py", line 83, in <module>`
`    selected_files = pdf_geno.select_files()`
 ` File "./utils/generate_ext_genome.py", line 38, in select_files`
`    classifier_results = self.classifier(file_paths)`
`  File "./utils/generate_ext_genome.py", line 24, in classifier`
`    return self.classifier_func(*args)`
`  File "./utils/generate_ext_genome.py", line 18, in <lambda>`
`    self.classifier_func = lambda *args:query_classifier(classifier_name, *args)`
`  File "/home/susobhan/research/EvadeML/utils/../lib/detector.py", line 22, in query_classifier`
`    results = server.query_classifier(classifier_name, file_paths, seed_sha1)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__`
`    return self.__send(self.__name, args)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request`
`    verbose=self.__verbose`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request`
`    return self.single_request(host, handler, request_body, verbose)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request`
`    return self.parse_response(response)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response`
`    return u.close()`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close`
`    raise Fault(**self._stack[0])`
`xmlrpclib.Fault: <Fault 1: "<type 'exceptions.ValueError'>:The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()">`

2. Hidost - 
`$ ./utils/generate_ext_genome.py hidost ~/research/datasets/benign 1`
`Traceback (most recent call last):`
 `File "./utils/generate_ext_genome.py", line 83, in <module>`
`    selected_files = pdf_geno.select_files()`
 ` File "./utils/generate_ext_genome.py", line 38, in select_files`
`    classifier_results = self.classifier(file_paths)`
`  File "./utils/generate_ext_genome.py", line 24, in classifier`
`    return self.classifier_func(*args)`
`  File "./utils/generate_ext_genome.py", line 18, in <lambda>`
`    self.classifier_func = lambda *args:query_classifier(classifier_name, *args)`
`  File "/home/susobhan/research/EvadeML/utils/../lib/detector.py", line 22, in query_classifier`
`    results = server.query_classifier(classifier_name, file_paths, seed_sha1)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__`
`    return self.__send(self.__name, args)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request`
`    verbose=self.__verbose`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request`
`    return self.single_request(host, handler, request_body, verbose)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request`
`    return self.parse_response(response)`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response`
`    return u.close()`
`  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close`
`    raise Fault(**self._stack[0])`
`xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'dict' object has no attribute 'decision_function'>`

Could you please help me with this? Apologies if I'm doing something wrong here.

**Comment by mzweilin** [comment]
XMLRPC is good at hiding bugs and error messages. I suggest you to call the service function defined in `detection_agent_server.py` directly to see what is going on inside.

Best,
-Weilin

**Comment by susobhang70** [comment]
After doing the same and resolving the issue causing the above, this is the followup error. This looks like a pdfrw error, and I have installed the modified pdfrw package that you list as a requirement. Any pointers regarding this?
```
Traceback (most recent call last):
  File "./utils/generate_ext_genome.py", line 84, in <module>
    selected_files = pdf_geno.select_files()
  File "./utils/generate_ext_genome.py", line 40, in select_files
    path_count = self.path_count(file_paths)
  File "./utils/generate_ext_genome.py", line 30, in path_count
    pdf_obj = PdfGenome.load_genome(fpath)
  File "/home/susobhan/research/EvadeML/utils/../lib/pdf_genome.py", line 18, in load_genome
    pdf_obj = PdfReader(pdf_file_path, slow_parsing=False)
  File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfreader.py", line 498, in __init__
    self.parsexref(source)
  File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfreader.py", line 322, in parsexref
    source.exception('Expected "xref" keyword')
  File "/usr/local/lib/python2.7/dist-packages/pdfrw/tokens.py", line 241, in exception
    raise PdfParseError(self.msg(*arg))
pdfrw.errors.PdfParseError: Expected "xref" keyword (line=7, col=1, token='230')
```

**Comment by mzweilin** [comment]
It looks like you have put a malformed PDF which lacks the cross reference table in [benign_sample_folder]. Could you try other benign PDFs for this?

**Comment by 201younghanlee** [comment]
> Hi! I'm trying to replicate the results from your EvadeML [GP attacks paper on PDFs](https://evademl.org/docs/evademl.pdf). I ran into a couple of issues running the code. I trained the two PDF classifier models, and when trying to run Step 2 (with Step 1 detection server running) - `./utils/generate_ext_genome.py [classifier_name] [benign_sample_folder] [file_number]` for the two classifiers, I get two different errors:
> 
> 1. PDFRate
>    `$ ./utils/generate_ext_genome.py pdfrate ~/research/datasets/benign 1`
>    `Traceback (most recent call last):`
>    `File "./utils/generate_ext_genome.py", line 83, in <module>`
>    `    selected_files = pdf_geno.select_files()`
>    ` File "./utils/generate_ext_genome.py", line 38, in select_files`
>    `    classifier_results = self.classifier(file_paths)`
>    `  File "./utils/generate_ext_genome.py", line 24, in classifier`
>    `    return self.classifier_func(*args)`
>    `  File "./utils/generate_ext_genome.py", line 18, in <lambda>`
>    `    self.classifier_func = lambda *args:query_classifier(classifier_name, *args)`
>    `  File "/home/susobhan/research/EvadeML/utils/../lib/detector.py", line 22, in query_classifier`
>    `    results = server.query_classifier(classifier_name, file_paths, seed_sha1)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__`
>    `    return self.__send(self.__name, args)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request`
>    `    verbose=self.__verbose`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request`
>    `    return self.single_request(host, handler, request_body, verbose)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request`
>    `    return self.parse_response(response)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response`
>    `    return u.close()`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close`
>    `    raise Fault(**self._stack[0])`
>    `xmlrpclib.Fault: <Fault 1: "<type 'exceptions.ValueError'>:The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()">`
> 2. Hidost -
>    `$ ./utils/generate_ext_genome.py hidost ~/research/datasets/benign 1`
>    `Traceback (most recent call last):`
>    `File "./utils/generate_ext_genome.py", line 83, in <module>`
>    `    selected_files = pdf_geno.select_files()`
>    ` File "./utils/generate_ext_genome.py", line 38, in select_files`
>    `    classifier_results = self.classifier(file_paths)`
>    `  File "./utils/generate_ext_genome.py", line 24, in classifier`
>    `    return self.classifier_func(*args)`
>    `  File "./utils/generate_ext_genome.py", line 18, in <lambda>`
>    `    self.classifier_func = lambda *args:query_classifier(classifier_name, *args)`
>    `  File "/home/susobhan/research/EvadeML/utils/../lib/detector.py", line 22, in query_classifier`
>    `    results = server.query_classifier(classifier_name, file_paths, seed_sha1)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__`
>    `    return self.__send(self.__name, args)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request`
>    `    verbose=self.__verbose`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request`
>    `    return self.single_request(host, handler, request_body, verbose)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request`
>    `    return self.parse_response(response)`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response`
>    `    return u.close()`
>    `  File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close`
>    `    raise Fault(**self._stack[0])`
>    `xmlrpclib.Fault: <Fault 1: "<type 'exceptions.AttributeError'>:'dict' object has no attribute 'decision_function'>`
> 
> Could you please help me with this? Apologies if I'm doing something wrong here.

@susobhang70 
Hello,
I am stuck in the same position.
How to you fix it?

Thanks for the hlep

**Comment by susobhang70** [comment]
@201younghanlee I think I did manage to figure it out - there might be malformed PDFs in your dataset. But I couldn't get it work after crossing that hurdle, as there were a lot of successive issues and we decided to not pursue this thread any further.
