### ISSUE TITLE
Hidost reproduction repo missing nppf file

### ISSUE THREAD

**Issue by Ryan-Wong-Ren-Wei** [uvasrg/EvadeML#6]
Hi,

I am trying to replicate the experiment results. After following the instructions on the hidost-reproduction repo (downloading the data tar file and doing sudo make on root directory), I can't find the features.nppf file required for the project.conf entry in the main EvadeML root directory. 

Am i required to do some work with the main hidost repo (https://github.com/srndic/hidost)? I was under the impression that the hidost-reproduction would completely reproduce the experiment and remove the need for the first repo. 

Any help in understanding the situation will be helpful. Thank you!

**Comment by mzweilin** [comment]
Hi @Ryan-Wong-Ren-Wei ,

Yes, `features.nppf` is from the authors of hidost. We don't have a license to redistribute everything that is required to reproduce the results. However, many research groups have been able to reproduce after reaching out to the original authors.

**Comment by Ryan-Wong-Ren-Wei** [comment]
I see, thank you for the help!

**Comment by Ryan-Wong-Ren-Wei** [comment]
May i ask then regarding the "model_path" pickled model file, is this file also directly from the authors of hidost?

**Comment by mzweilin** [comment]
> May i ask then regarding the "model_path" pickled model file, is this file also directly from the authors of hidost?

Yes.

**Comment by Ryan-Wong-Ren-Wei** [comment]
I see, thank you for your assistance, will close the issue now. Have a good week!
