### ISSUE TITLE
-o argument doesn't exist in gp.py script

### ISSUE THREAD

**Issue by Ryan-Wong-Ren-Wei** [uvasrg/EvadeML#7]
It is listed in the help message that we can specify an oracle (like cuckoo in the case of your experiment in the research paper) using the "-o" argument but it doesn't seem to work? I also took a look at the gp.py script and there is no "-o" argument at all. Is this intended? If so, is there any way we can reproduce the experiment using cuckoo as an oracle?

**Comment by mzweilin** [comment]
Sorry for the confusion. The help message was outdated since we hardcoded Cuckoo as the oracle.

Here comes an example of using gp.py:
https://github.com/uvasrg/EvadeML/blob/master/batch.py#L39

**Comment by Ryan-Wong-Ren-Wei** [comment]
I see. Thank you for the information, I have successfully generated the external genome. Hope you don't mind me asking more questions but where do i put the actual malware samples that i wish to use as seeds. Do i put them in the ./samples/seeds directory?
